### ISSUE TITLE
Export rows repeats itself after 1000 items/rows

### ISSUE THREAD

**Issue by Melleschepers** [degdigital/magento2-customreports#36]
First of all; nice module 😄 ! 
I'm using version 2.0.3.

Recently I installed this module and ran into the following problem that the rows are repeated after 1000 rows when automated exporting. This issue is only present in the automated export (so not in the manual "export to [file] export" button) .

The reason for this is the "setPageSize(1000);" in file https://github.com/degdigital/magento2-customreports/blob/4fdcab12600855601aa3ea2495e1bc4072aaeafc/Model/Service/ExportReportService.php#L80

Is it safe to just comment out this line? Or is there a better approach? Thanks! 😃

**Comment by jantzenw** [comment]
Hi,

Sorry for the long delay. This should be fixed now in v2.0.6. See this commit: https://github.com/degdigital/magento2-customreports/commit/6a45fbc5930abc7b09ed491eb29ecadf7d128bb6

From that commit message: 

We could think of two possible ways to resolve this:
1) Remove the query's LIMIT
2) Fix the code to correctly use the query's LIMIT + OFFSET filters, which is what the code was trying to do before this change.

Both have significant downsides. #1 can drastically increase the memory footprint of the export logic, because now the full results are loaded into memory. #2 can result in exceptionally slow exports, because LIMIT + OFFSET causes a large query to be run multiple times, PLUS the fact that OFFSET can have extremely bad performance with large values.

We went with option #1. We found that the performance impact of the export and the load on the database of #2 can be too significant with large, heavy queries. With #1, a report CSV would have to be in somewhere over 100MB before the risk of hitting the PHP memory limit is significant. We feel this is a much smaller likelihood of happening, and for clients that would need to be exporting that much data would have the technical expertise to #2 if necessary, or shrink the query results somehow. #2 affects a greater number of users and causes a frustrating performance hit.
